//
//  AppGlyphs.swift
//  hungrynow
//
//  ONE icon set for the whole app.
//
//  The mockups' rule, from `shared.css`: every glyph is drawn on the same 24-unit
//  grid with the same rounded caps, and screens must draw from this one set rather
//  than from hand-made copies that drift apart.
//
//  **The glyphs are now SVG imagesets in `Assets.xcassets`, not Swift `Shape`s.**
//  Each `glyph-*.imageset` carries `preserves-vector-representation` and a
//  `template` rendering intent, so the artwork scales as a vector and takes its
//  colour from the environment's tint. The stroke weight is baked into the SVG in
//  grid units, which is how the mockups author it — an SVG scales its stroke with
//  the viewBox, so a glyph keeps its authored weight at every display size without
//  the `GlyphMetrics.stroke` conversion the `Shape` versions each had to do.
//
//  Consequences worth knowing:
//  - Colour comes from `.foregroundColor` / tint, not a `.stroke(_:)` argument.
//  - A call site can no longer pick its own stroke weight. That is the point.
//  - Editing a glyph means editing its `.svg`, not Swift path code.
//  - **Never `currentColor` in these files.** It resolves against an inherited CSS
//    colour, which the mockups provide and an asset catalog does not. iOS 17+
//    tolerates it; iOS 16 leaves it unresolved and the glyph renders BLANK — all
//    20 did, and it was invisible on a modern dev device (2026-09-18). Bake a
//    literal colour; `template-rendering-intent` re-tints it anyway, so the baked
//    value never reaches the screen.
//

import SwiftUI

/// The app's icon set. One case per glyph, one imageset per case.
///
/// An enum rather than raw `Image("glyph-...")` strings, deliberately: it keeps the
/// "one icon set" rule enforceable — a screen cannot quietly introduce a hand-drawn
/// one-off or typo an asset name into a silent blank.
enum AppGlyph: String, CaseIterable {
    case search              = "glyph-search"
    case check               = "glyph-check"
    case locationPin         = "glyph-location-pin"
    case tryAnother          = "glyph-try-another"
    case directions          = "glyph-directions-arrow"
    case star                = "glyph-star"
    case starFill            = "glyph-star-fill"
    case externalLink        = "glyph-external-link"
    case navigationPointer   = "glyph-navigation-pointer"
    case chevronLeft         = "glyph-chevron-left"
    case chevronRight        = "glyph-chevron-right"
    case cutlery             = "glyph-cutlery"
    case refreshArrows       = "glyph-refresh-arrows"
    case walkingPerson       = "glyph-walking-person"
    case settings            = "glyph-settings"
    case reload              = "glyph-reload"
    case foodNoodleBowl      = "glyph-food-noodle-bowl"
    case foodSkewer          = "glyph-food-skewer"
    case foodCup             = "glyph-food-cup"
    case foodRiceBowl        = "glyph-food-rice-bowl"

    /// The glyph as a template image, sized square and tinted by `color`.
    ///
    /// Square by construction: every glyph is authored on a square viewBox, so a
    /// non-square frame would letterbox it rather than stretch it, and the caller
    /// almost never wants that.
    @ViewBuilder
    func image(size: CGFloat, color: Color) -> some View {
        Image(rawValue)
            .renderingMode(.template)
            .resizable()
            .scaledToFit()
            .frame(width: size, height: size)
            .foregroundColor(color)
    }
}

/// Picks a glyph for a model-generated `foodCategory` (1-3 words, e.g. "Ramen",
/// "Babi Guling", "Coffee").
///
/// **A stopgap, and it will mis-map.** The real answer is the bundled `foodCategory`
/// icon library on the checklist; this is four shapes and a keyword table standing in
/// for it. Deliberately CONSERVATIVE — anything unmatched falls back to the generic
/// bowl rather than guessing, because a wrong glyph beside correct text is worse than
/// a neutral one. `foodCategory` is free text from Gemini, not an enum, so no table
/// can be complete.
///
/// Keywords are Indonesian as well as English: the market is Indonesia, and the model
/// returns local dish names ("Nasi", "Mie", "Sate", "Kopi") far more often than
/// English ones.
///
/// **Known drift risk, named rather than hidden:** screen 05's radar pins are the same
/// four drawings, and they live inside `radar-sweep.json`, generated by
/// `build-radar-lottie.py` from the same mockup source. Change a food glyph's `.svg`
/// and the Lottie copy must be regenerated to match.
extension AppGlyph {
    static func forCategory(_ category: String) -> AppGlyph {
        let text = category.lowercased()

        func matches(_ keywords: [String]) -> Bool {
            keywords.contains { text.contains($0) }
        }

        if matches(["coffee", "kopi", "tea", "teh", "juice", "jus", "drink", "minuman",
                    "cafe", "kafe", "boba", "smoothie", "espresso", "latte"]) {
            return .foodCup
        }
        if matches(["satay", "sate", "skewer", "kebab", "grill", "bakar", "bbq",
                    "barbecue", "yakitori", "tusuk"]) {
            return .foodSkewer
        }
        if matches(["rice", "nasi", "curry", "kari", "rendang", "gudeg", "guling",
                    "padang", "poke", "don", "bowl"]) {
            return .foodRiceBowl
        }
        // Noodles and soups share the generic bowl, which is also the fallback — see
        // `.hero-photo-fallback` in the mockup, which uses this same drawing.
        return .foodNoodleBowl
    }
}
